# Generated by Django 6.0.7 on 2026-07-31 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0002_schoolinvitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("sms_phone", models.CharField(blank=True, max_length=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_preference",
                        to="schools.schoolmembership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=60)),
                ("name", models.CharField(max_length=120)),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("SMS", "SMS")], max_length=10
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("REPORT", "Published report"),
                            ("ATTENDANCE", "Attendance"),
                            ("SCHOOL_EVENT", "School event"),
                            ("BALANCE", "Fee balance"),
                            ("GENERAL", "General notice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject_template", models.CharField(blank=True, max_length=200)),
                ("body_template", models.TextField()),
                ("contains_sensitive_data", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_templates",
                        to="schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("SMS", "SMS")], max_length=10
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("REPORT", "Published report"),
                            ("ATTENDANCE", "Attendance"),
                            ("SCHOOL_EVENT", "School event"),
                            ("BALANCE", "Fee balance"),
                            ("GENERAL", "General notice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("business_reference", models.CharField(max_length=160)),
                ("idempotency_key", models.CharField(max_length=64)),
                ("destination", models.CharField(max_length=254)),
                ("rendered_subject", models.CharField(blank=True, max_length=200)),
                ("rendered_body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        max_length=12,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=160)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="message_intents",
                        to="schools.schoolmembership",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_intents",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_message_intents",
                        to="schools.schoolmembership",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="message_intents",
                        to="communications.messagetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("succeeded", models.BooleanField(default=False)),
                ("provider", models.CharField(max_length=40)),
                ("provider_message_id", models.CharField(blank=True, max_length=160)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_attempts",
                        to="communications.messageintent",
                    ),
                ),
            ],
            options={
                "ordering": ["-attempted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("intent", "attempt_number"),
                        name="unique_message_attempt",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="messagetemplate",
            constraint=models.UniqueConstraint(
                fields=("school", "code"), name="unique_school_message_template"
            ),
        ),
        migrations.AddIndex(
            model_name="messageintent",
            index=models.Index(
                fields=["status", "next_attempt_at"], name="message_delivery_queue_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="messageintent",
            constraint=models.UniqueConstraint(
                fields=("school", "idempotency_key"), name="unique_school_message_event"
            ),
        ),
    ]
