# Generated by Django 6.0.7 on 2026-08-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0006_notification_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communicationpreference",
            name="sms_enabled",
            field=models.BooleanField(default=False, verbose_name="SMS enabled"),
        ),
        migrations.AlterField(
            model_name="communicationpreference",
            name="sms_phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="SMS phone"),
        ),
    ]
