# Generated by Django 6.0.7 on 2026-08-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0007_alter_communicationpreference_sms_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("LESSON_REVIEW", "Lesson review"),
                    ("GRADE_REVIEW", "Grade review"),
                    ("ASSIGNMENT", "Assignment submission"),
                    ("STAFF_ASSIGNMENT", "Teaching assignment"),
                    ("ATTENDANCE", "Attendance alert"),
                    ("REPORT_REVIEW", "Report review"),
                    ("FINANCE", "Finance alert"),
                    ("ANALYTICS", "Analytics alert"),
                    ("BILLING", "Billing"),
                ],
                max_length=24,
            ),
        ),
    ]
