# Generated by Django 6.0.8 on 2026-09-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_seed_individual_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenseplan",
            name="code",
            field=models.CharField(
                choices=[
                    ("STARTER", "Starter"),
                    ("STANDARD", "Standard"),
                    ("PARTNER", "Partner"),
                    ("INDIVIDUAL", "Individual Teacher"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
    ]
