from django import forms

from .models import Assessment, AssessmentCategory, GradeScheme


class AssessmentForm(forms.ModelForm):
    class Meta:
        model = Assessment
        fields = ["category", "title", "max_score", "due_at", "status"]
        widgets = {"due_at": forms.DateTimeInput(attrs={"type": "datetime-local"})}

    def __init__(self, *args, offering, **kwargs):
        self.offering = offering
        super().__init__(*args, **kwargs)
        self.fields["category"].queryset = AssessmentCategory.objects.filter(
            scheme__school=offering.school,
            scheme__academic_year=offering.term.academic_year,
            scheme__status=GradeScheme.Status.ACTIVE,
        ).select_related("scheme")
        self.instance.school = offering.school
        self.instance.offering = offering


class GradeWorkbookUploadForm(forms.Form):
    workbook = forms.FileField(
        help_text="Upload the completed Nyansa .xlsx roster template (maximum 2 MB)."
    )

    def clean_workbook(self):
        workbook = self.cleaned_data["workbook"]
        if not workbook.name.lower().endswith(".xlsx"):
            raise forms.ValidationError("Upload an .xlsx workbook generated by Nyansa.")
        if workbook.size > 2 * 1024 * 1024:
            raise forms.ValidationError("Workbook must be 2 MB or smaller.")
        return workbook
