# Generated by Django 6.0.7 on 2026-08-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="earlywarningpolicy",
            name="metric",
            field=models.CharField(
                choices=[
                    ("LOW_AVERAGE", "Low academic average"),
                    ("LOW_SUBMISSION_RATE", "Low submission rate"),
                    ("MISSING_GRADES", "Missing approved grade entries"),
                ],
                max_length=20,
            ),
        ),
    ]
