# Generated by Django 6.0.7 on 2026-08-09 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0007_school_report_signatures"),
        ("tutor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorsession",
            name="mode",
            field=models.CharField(
                choices=[
                    ("TEACH_ME", "Teach Me"),
                    ("GUIDE_ME", "Guide Me"),
                    ("HINT", "Give Me a Hint"),
                    ("PRACTICE", "Practice With Me"),
                    ("CHECK_MY_WORK", "Check My Work"),
                    ("EXPLAIN_MY_MISTAKE", "Explain My Mistake"),
                    ("REVISE_WITH_ME", "Revise With Me"),
                    ("EXAM_MODE", "Exam Mode"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TutorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disabled_modes", models.JSONField(blank=True, default=list)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_settings",
                        to="schools.school",
                    ),
                ),
            ],
        ),
    ]
