# Generated by Django 6.0.7 on 2026-08-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0002_alter_tutorsession_mode_tutorsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorsettings",
            name="allow_final_answer_reveal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tutorsettings",
            name="max_hint_depth",
            field=models.PositiveIntegerField(default=4),
        ),
    ]
