# Generated by Django 6.0.7 on 2026-08-10 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_material_extracted_text"),
        ("mastery", "0001_initial"),
        ("tutor", "0003_tutorsettings_allow_final_answer_reveal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorsession",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutor_sessions",
                to="courses.material",
            ),
        ),
        migrations.AddField(
            model_name="tutorsession",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutor_sessions",
                to="mastery.topic",
            ),
        ),
    ]
