# Generated by Django 6.0.7 on 2026-08-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0004_tutorsession_material_tutorsession_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorsettings",
            name="daily_usage_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
