# Generated by Django 6.0.7 on 2026-08-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0005_tutorsettings_daily_usage_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorsettings",
            name="max_difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="hard",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tutorsettings",
            name="min_difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="easy",
                max_length=10,
            ),
        ),
    ]
