# Generated by Django 6.0.7 on 2026-08-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0006_tutorsettings_max_difficulty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorsettings",
            name="restricted_period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tutorsettings",
            name="restricted_period_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
