# Generated by Django 6.0.7 on 2026-07-08 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_studydocument_studyquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(help_text='e.g. Basic 5, JHS 2', max_length=100)),
                ('week_ending', models.DateField()),
                ('strand_topic', models.CharField(help_text='e.g. Numbers, Reproduction', max_length=200)),
                ('content_standard', models.TextField(blank=True)),
                ('learning_indicator', models.TextField()),
                ('performance_indicator', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=300)),
                ('resources', models.CharField(blank=True, max_length=300)),
                ('num_days', models.PositiveIntegerField(default=5)),
                ('generated_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notes', to='courses.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
