# Generated by Django 6.0.7 on 2026-07-31 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        ("schools", "0002_schoolinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonnote",
            name="current_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lessonnote",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonnote",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_lesson_notes",
                to="schools.schoolmembership",
            ),
        ),
        migrations.AddField(
            model_name="lessonnote",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_REVIEW", "Pending Review"),
                    ("SENT_BACK", "Sent Back"),
                    ("APPROVED", "Approved"),
                ],
                default="DRAFT",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="lessonnote",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonnote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="LessonNoteEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("COMMENT", "Comment"),
                            ("SUBMITTED", "Submitted"),
                            ("SENT_BACK", "Sent Back"),
                            ("APPROVED", "Approved"),
                            ("REOPENED", "Reopened"),
                            ("REVISED", "Revised"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lesson_note_events",
                        to="schools.schoolmembership",
                    ),
                ),
                (
                    "lesson_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="dashboard.lessonnote",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LessonNoteNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lesson_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="dashboard.lessonnote",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_note_notifications",
                        to="schools.schoolmembership",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LessonNoteVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                ("reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lesson_note_versions",
                        to="schools.schoolmembership",
                    ),
                ),
                (
                    "lesson_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="dashboard.lessonnote",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lesson_note", "version_number"),
                        name="unique_lesson_note_version",
                    )
                ],
            },
        ),
    ]
