# Generated by Django 6.0.8 on 2026-09-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0002_lessonnote_current_version_lessonnote_reviewed_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonnote",
            name="class_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonnote",
            name="core_competencies",
            field=models.CharField(
                blank=True,
                help_text="e.g. Communication and Collaboration; Critical Thinking",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="lessonnote",
            name="duration",
            field=models.CharField(
                blank=True, help_text="e.g. 1 hour, 40 minutes", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="lessonnote",
            name="sub_strand",
            field=models.CharField(
                blank=True, help_text="e.g. Cutting/Shaping", max_length=200
            ),
        ),
    ]
