# Generated by Django 6.0.8 on 2026-09-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_schemeoflearning_studentnote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonnote",
            name="class_size",
            field=models.PositiveIntegerField(
                blank=True, help_text="e.g. 35", null=True
            ),
        ),
        migrations.AlterField(
            model_name="lessonnote",
            name="content_standard",
            field=models.TextField(
                blank=True,
                help_text="Optional - the AI will infer one from the topic if left blank.",
            ),
        ),
        migrations.AlterField(
            model_name="lessonnote",
            name="learning_indicator",
            field=models.TextField(
                help_text="e.g. B7.3.1.1.1: Classify and use measuring and marking out tools and equipment for production"
            ),
        ),
        migrations.AlterField(
            model_name="lessonnote",
            name="performance_indicator",
            field=models.TextField(
                blank=True,
                help_text="Optional - the AI will infer reasonable ones if left blank.",
            ),
        ),
        migrations.AlterField(
            model_name="lessonnote",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Optional - defaults to a standard curriculum textbook if left blank.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="lessonnote",
            name="resources",
            field=models.CharField(
                blank=True,
                help_text="Optional - defaults to standard classroom resources if left blank.",
                max_length=300,
            ),
        ),
    ]
