# Generated by Django 6.0.8 on 2026-09-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_lessonnote_class_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonnote",
            name="num_days",
        ),
        migrations.AddField(
            model_name="lessonnote",
            name="teaching_days",
            field=models.CharField(
                blank=True,
                help_text="Which days this lesson meets, e.g. Monday, Wednesday, Friday",
                max_length=100,
            ),
        ),
    ]
