# Generated by Codex on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_lessonnote_teacher_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonnote",
            name="week_number",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Week number for this lesson note, e.g. 1 for Week 1.",
            ),
        ),
    ]
