# Generated by Django 6.0.7 on 2026-07-31 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0002_schoolinvitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuardianLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("MOTHER", "Mother"),
                            ("FATHER", "Father"),
                            ("GUARDIAN", "Guardian"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("REVOKED", "Revoked")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("is_primary_contact", models.BooleanField(default=False)),
                (
                    "authorization_reference",
                    models.CharField(
                        help_text="School-held consent or verification reference.",
                        max_length=120,
                    ),
                ),
                ("authorized_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorized_guardian_links",
                        to="schools.schoolmembership",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_links",
                        to="schools.schoolmembership",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revoked_guardian_links",
                        to="schools.schoolmembership",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_links",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_guardian_links",
                        to="schools.schoolmembership",
                    ),
                ),
            ],
            options={
                "ordering": ["student__user__last_name", "guardian__user__last_name"],
                "indexes": [
                    models.Index(
                        fields=["school", "guardian", "status"],
                        name="guardian_access_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "guardian", "student"),
                        name="unique_guardian_student_link",
                    )
                ],
            },
        ),
    ]
