# Generated by Django 6.0.7 on 2026-07-31 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("schools", "0002_schoolinvitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_position", models.BooleanField(default=False)),
                (
                    "pass_mark",
                    models.DecimalField(decimal_places=2, default=50, max_digits=5),
                ),
                (
                    "promotion_average",
                    models.DecimalField(decimal_places=2, default=50, max_digits=5),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_policy",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_policies",
                        to="schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TermReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending review"),
                            ("RETURNED", "Sent back"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "average_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("conduct", models.CharField(blank=True, max_length=120)),
                ("teacher_remark", models.TextField(blank=True)),
                ("administrator_remark", models.TextField(blank=True)),
                (
                    "promotion_outcome",
                    models.CharField(
                        choices=[
                            ("PROMOTED", "Promoted"),
                            ("REPEATED", "Repeated"),
                            ("PENDING", "Pending decision"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prepared_term_reports",
                        to="schools.schoolmembership",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_term_reports",
                        to="schools.schoolmembership",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="term_reports",
                        to="schools.school",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="term_reports",
                        to="academics.schoolclass",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="term_reports",
                        to="schools.schoolmembership",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="term_reports",
                        to="academics.term",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "school_class__name",
                    "student__user__last_name",
                    "student_id",
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportWorkflowEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("GENERATED", "Generated"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("RETURNED", "Returned"),
                            ("PUBLISHED", "Published"),
                            ("REOPENED", "Reopened"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending review"),
                            ("RETURNED", "Sent back"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending review"),
                            ("RETURNED", "Sent back"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                        ],
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_workflow_events",
                        to="schools.schoolmembership",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_events",
                        to="reports.termreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="termreport",
            index=models.Index(
                fields=["school", "term", "status"], name="report_school_term_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="termreport",
            constraint=models.UniqueConstraint(
                fields=("school_class", "term", "student"),
                name="unique_student_term_report",
            ),
        ),
    ]
