# Generated by Django 6.0.7 on 2026-08-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_require_school_ownership"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="extracted_text",
            field=models.TextField(blank=True),
        ),
    ]
