# Generated by Django 6.0.8 on 2026-09-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_material_extracted_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Course code, e.g. MATH101. Tertiary only.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="credit_hours",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Credit hours. Tertiary only.", null=True
            ),
        ),
    ]
