# Generated by Django 6.0.7 on 2026-08-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mastery", "0004_studygoal"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True, related_name="unlocks", to="mastery.topic"
            ),
        ),
    ]
