# Generated by Django 6.0.7 on 2026-08-12 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mastery", "0005_topic_prerequisites"),
        ("schools", "0007_school_report_signatures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remediationplan",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remediation_plans",
                to="mastery.topic",
            ),
        ),
        migrations.AlterField(
            model_name="studygoal",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_goals",
                to="mastery.topic",
            ),
        ),
        migrations.CreateModel(
            name="TopicRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_name", models.CharField(max_length=120)),
                ("new_name", models.CharField(max_length=120)),
                ("previous_strand_name", models.CharField(max_length=120)),
                ("new_strand_name", models.CharField(max_length=120)),
                ("reason", models.CharField(max_length=300)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="topic_revisions",
                        to="schools.schoolmembership",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="mastery.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at", "-id"],
            },
        ),
    ]
