# Generated by Django 6.0.7 on 2026-07-31 20:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("schools", "0002_schoolinvitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("code", models.SlugField(max_length=30)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage contribution to the final result.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="academics.subjectoffering",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="schools.school",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="gradebook.assessmentcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["offering_id", "due_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="GradeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online activity"),
                            ("MANUAL", "Manual entry"),
                            ("IMPORT", "Spreadsheet import"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_entries",
                        to="gradebook.assessment",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_grade_entries",
                        to="schools.schoolmembership",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_entries",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_entries",
                        to="schools.schoolmembership",
                    ),
                ),
            ],
            options={
                "ordering": ["assessment_id", "student_id"],
            },
        ),
        migrations.CreateModel(
            name="GradeScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_schemes",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_schemes",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-academic_year__start_date", "name"],
            },
        ),
        migrations.AddField(
            model_name="assessmentcategory",
            name="scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="gradebook.gradescheme",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.UniqueConstraint(
                fields=("offering", "category", "title"),
                name="unique_assessment_title_per_category",
            ),
        ),
        migrations.AddIndex(
            model_name="gradeentry",
            index=models.Index(
                fields=["school", "student", "status"], name="grade_school_student_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gradeentry",
            constraint=models.UniqueConstraint(
                fields=("assessment", "student"), name="unique_student_assessment_grade"
            ),
        ),
        migrations.AddConstraint(
            model_name="gradescheme",
            constraint=models.UniqueConstraint(
                fields=("school", "academic_year", "name"),
                name="unique_grade_scheme_name_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentcategory",
            constraint=models.UniqueConstraint(
                fields=("scheme", "code"), name="unique_category_code_per_scheme"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentcategory",
            constraint=models.UniqueConstraint(
                fields=("scheme", "order"), name="unique_category_order_per_scheme"
            ),
        ),
    ]
