# Generated by Django 6.0.7 on 2026-07-31 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0001_initial"),
        ("schools", "0002_schoolinvitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIEW", "Awaiting confirmation"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PREVIEW",
                        max_length=12,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("valid_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="gradebook.assessment",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_grade_imports",
                        to="schools.schoolmembership",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_import_batches",
                        to="schools.school",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_grade_imports",
                        to="schools.schoolmembership",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="GradeImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("raw_student_id", models.CharField(blank=True, max_length=100)),
                ("raw_score", models.CharField(blank=True, max_length=100)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VALID", "Ready"),
                            ("ERROR", "Error"),
                            ("SKIPPED", "Blank score"),
                            ("IMPORTED", "Imported"),
                        ],
                        max_length=10,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=500)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="gradebook.gradeimportbatch",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_import_rows",
                        to="schools.schoolmembership",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
            },
        ),
        migrations.AddIndex(
            model_name="gradeimportbatch",
            index=models.Index(
                fields=["school", "status", "uploaded_at"],
                name="import_school_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradeimportrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "row_number"), name="unique_import_batch_row"
            ),
        ),
        migrations.AddConstraint(
            model_name="gradeimportrow",
            constraint=models.UniqueConstraint(
                condition=models.Q(("student__isnull", False)),
                fields=("batch", "student"),
                name="unique_import_batch_student",
            ),
        ),
    ]
