# Generated by Django 6.0.7 on 2026-07-31 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0002_gradeimportbatch_gradeimportrow_and_more"),
        ("quizzes", "0006_quiz_assessment_type"),
        ("schools", "0002_schoolinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="legacy_assignment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gradebook_assessment",
                to="quizzes.assignment",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="legacy_quiz",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gradebook_assessment",
                to="quizzes.quiz",
            ),
        ),
        migrations.AddField(
            model_name="gradeentry",
            name="review_note",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="gradeentry",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("NOT_REVIEWED", "Not submitted"),
                    ("PENDING", "Pending review"),
                    ("APPROVED", "Approved"),
                    ("RETURNED", "Returned"),
                ],
                default="NOT_REVIEWED",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="gradeentry",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gradeentry",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_grade_entries",
                to="schools.schoolmembership",
            ),
        ),
        migrations.CreateModel(
            name="GradeEntryRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("CORRECTED", "Corrected"),
                            ("IMPORTED", "Imported"),
                            ("SYNCED", "Legacy synchronization"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "previous_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("new_score", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        max_length=10,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        max_length=10,
                    ),
                ),
                (
                    "previous_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ONLINE", "Online activity"),
                            ("MANUAL", "Manual entry"),
                            ("IMPORT", "Spreadsheet import"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "new_source",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online activity"),
                            ("MANUAL", "Manual entry"),
                            ("IMPORT", "Spreadsheet import"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_entry_revisions",
                        to="schools.schoolmembership",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="gradebook.gradeentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GradeReviewDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("RETURNED", "Returned")],
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_decisions",
                        to="gradebook.gradeentry",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_review_decisions",
                        to="schools.schoolmembership",
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at", "-id"],
            },
        ),
    ]
