# Generated by Django 6.0.7 on 2026-08-09 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gradebook",
            "0003_assessment_legacy_assignment_assessment_legacy_quiz_and_more",
        ),
        ("mastery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to="mastery.topic",
            ),
        ),
    ]
