# Generated by Django 6.0.8 on 2026-09-05 04:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_subject_code_subject_credit_hours"),
        ("gradebook", "0004_assessment_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradescheme",
            name="boundary_type",
            field=models.CharField(
                choices=[
                    ("FIXED", "Fixed scale (e.g. GES 1-9, code-defined)"),
                    ("CONFIGURABLE_PERCENTAGE", "School-defined percentage bands"),
                    ("DYNAMIC_MARK", "Per-subject mark boundaries (e.g. Cambridge)"),
                ],
                default="FIXED",
                help_text="How GradeBoundary rows for this scheme should be interpreted.",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="GradeBoundary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_series",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'June 2026'. Record-keeping only for now - lookup doesn't key on it yet.",
                        max_length=40,
                    ),
                ),
                (
                    "grade",
                    models.CharField(help_text="e.g. A*, A, B, 1, 2", max_length=5),
                ),
                ("minimum_mark", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "reference_max_mark",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100"),
                        help_text="What minimum_mark is out of - enter boundaries exactly as published.",
                        max_digits=6,
                    ),
                ),
                (
                    "grade_point",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional GPA value, e.g. 4.0.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boundaries",
                        to="gradebook.gradescheme",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for a scheme-wide band. Required in practice for DYNAMIC_MARK schemes.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_boundaries",
                        to="courses.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["scheme_id", "subject_id", "-minimum_mark"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scheme", "subject", "grade"),
                        name="unique_boundary_grade",
                    )
                ],
            },
        ),
    ]
