# Generated by Django 6.0.7 on 2026-08-25 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
        ("schools", "0008_school_suku360_id_schoolmembership_suku360_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suku360RosterCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=128)),
                (
                    "base_url",
                    models.URLField(
                        help_text="Suku360 API base URL, e.g. https://api.suku360.com"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suku360_roster_credential",
                        to="schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PROCESSING",
                        max_length=12,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_batches",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("ACADEMIC_YEAR", "Academic Year"),
                            ("TERM", "Term"),
                            ("SCHOOL_CLASS", "School Class"),
                            ("STUDENT", "Student"),
                            ("TEACHER", "Teacher"),
                            ("ENROLLMENT", "Class Enrollment"),
                            ("TEACHER_ASSIGNMENT", "Teacher Assignment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("suku360_id", models.CharField(max_length=64)),
                ("nyansa_object_id", models.CharField(blank=True, max_length=32)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("UNCHANGED", "Unchanged"),
                            ("ERROR", "Error"),
                        ],
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="integrations.syncbatch",
                    ),
                ),
            ],
        ),
    ]
