# Generated by Django 6.0.7 on 2026-08-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_suku360rostercredential_syncbatch_syncrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="SsoNonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nonce", models.CharField(db_index=True, max_length=64, unique=True)),
                ("used_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
