# Generated by Django 6.0.7 on 2026-08-25 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0007_school_report_signatures"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="suku360_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Suku360's own school id, once synced. Nyansa-local until then.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="schoolmembership",
            name="suku360_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Suku360's own Membership/Student id for this person at this school, once synced.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("suku360_id__isnull", False)),
                fields=("school", "suku360_id"),
                name="unique_school_member_suku360_id",
            ),
        ),
    ]
