# Generated by Django 6.0.7 on 2026-08-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0008_school_suku360_id_schoolmembership_suku360_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="offers_shs",
            field=models.BooleanField(
                default=False, help_text="General Senior High School (SHS 1-3)."
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="offers_stem",
            field=models.BooleanField(
                default=False,
                help_text="A dedicated STEM-focused senior high programme, distinct from general SHS.",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="offers_tvet",
            field=models.BooleanField(
                default=False,
                help_text="Technical and Vocational Education and Training - a separate institution type from SHS/STEM.",
            ),
        ),
    ]
