# Generated by Django 6.0.8 on 2026-09-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0009_school_offers_shs_school_offers_stem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="education_system",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic School"),
                    ("SENIOR_HIGH", "Senior High School"),
                    ("CAMBRIDGE", "Cambridge International"),
                    ("TERTIARY", "Tertiary"),
                ],
                default="BASIC",
                help_text="The curriculum and grading standard this school follows.",
                max_length=16,
            ),
        ),
    ]
