# Generated by Django 6.0.8 on 2026-09-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0010_school_education_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="is_personal",
            field=models.BooleanField(
                default=False,
                help_text="A one-teacher personal space (no invited members), not a real institution.",
            ),
        ),
    ]
