# Generated by Django 6.0.7 on 2026-07-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of attempts a student can make'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Time limit for students to complete this quiz, in minutes'),
        ),
    ]
