# Generated by Django 6.0.7 on 2026-07-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Optional deadline after which students cannot submit', null=True),
        ),
    ]
