# Generated by Django 6.0.7 on 2026-07-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='assessment_type',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('EXAM', 'Exam')], default='QUIZ', max_length=10),
        ),
    ]
