# Generated by Django 6.0.7 on 2026-08-10 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mastery", "0001_initial"),
        ("quizzes", "0006_quiz_assessment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="mastery.topic",
            ),
        ),
    ]
