# Generated by Django 6.0.7 on 2026-08-10 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0007_question_topic"),
        ("schools", "0007_school_report_signatures"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                default="PUBLISHED",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="QuizGenerationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("require_review", models.BooleanField(default=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_generation_settings",
                        to="schools.school",
                    ),
                ),
            ],
        ),
    ]
