# Generated by Django 6.0.7 on 2026-08-11 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0009_bankquestion_bankquestionchoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="grading_rubric",
        ),
        migrations.CreateModel(
            name="RubricCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What does 'good' look like for this criterion?",
                    ),
                ),
                ("max_points", models.FloatField(default=10)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="quizzes.assignment",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CriterionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_score", models.FloatField(blank=True, null=True)),
                ("ai_feedback", models.TextField(blank=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterion_scores",
                        to="quizzes.assignmentsubmission",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizzes.rubriccriterion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("submission", "criterion"),
                        name="unique_submission_criterion",
                    )
                ],
            },
        ),
    ]
