# Generated by Django 6.0.7 on 2026-08-29 17:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0002_schoolclass_suku360_id_teacherassignment_suku360_id_and_more",
        ),
        ("quizzes", "0010_remove_assignment_grading_rubric_rubriccriterion_and_more"),
        ("schools", "0008_school_suku360_id_schoolmembership_suku360_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="ai_suggested_feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="ai_suggested_points",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="file_answer",
            field=models.FileField(
                blank=True, null=True, upload_to="exam_essay_answers/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="graded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="points_awarded",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="teacher_feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="points",
            field=models.FloatField(
                default=1.0, help_text="Max marks for this question."
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="essay_weight_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Essay questions' share of the combined score (0-100). The rest is the objective share.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="offerings",
            field=models.ManyToManyField(
                blank=True,
                help_text="For exams: the class/subject offerings sitting this exam. Leave empty for a subject-wide quiz.",
                related_name="quizzes",
                to="academics.subjectoffering",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="require_webcam_snapshots",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="quiz",
            name="results_published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set once results are actually released to students.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="results_release_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Required when results release mode is Scheduled.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="results_release_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INSTANT", "Instant"),
                    ("SCHEDULED", "Scheduled"),
                    ("MANUAL", "Manual publish"),
                ],
                default="INSTANT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="snapshot_interval_seconds",
            field=models.PositiveIntegerField(blank=True, default=90),
        ),
        migrations.AddField(
            model_name="quiz",
            name="starts_at",
            field=models.DateTimeField(
                blank=True,
                help_text="For exams: when this exam window opens. Leave blank for quizzes without a fixed start.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="camera_consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="camera_consent_given",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="submission",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="For exams: the server-side cutoff for this attempt (start + time limit, capped at the exam deadline).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="flagged_for_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="submission",
            name="started_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="bankquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("MCQ", "Multiple Choice"),
                    ("SHORT", "Short Answer"),
                    ("ESSAY", "Essay / Subjective"),
                ],
                default="MCQ",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("MCQ", "Multiple Choice"),
                    ("SHORT", "Short Answer"),
                    ("ESSAY", "Essay / Subjective"),
                ],
                default="MCQ",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Null while an exam attempt is still in progress.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ExamIntegrityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("TAB_HIDDEN", "Tab hidden"),
                            ("BLUR", "Window lost focus"),
                            ("FULLSCREEN_EXIT", "Exited fullscreen"),
                            ("CAMERA_DENIED", "Camera permission denied"),
                            ("CAMERA_ERROR", "Camera error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("detail", models.CharField(blank=True, max_length=255)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_events",
                        to="quizzes.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="exam_snapshots/%Y/%m/%d/")),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("INTERVAL", "Periodic interval"),
                            ("TAB_SWITCH", "Tab switch"),
                            ("BLUR", "Window blur"),
                            ("ATTEMPT_START", "Attempt start"),
                        ],
                        default="INTERVAL",
                        max_length=20,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="quizzes.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["captured_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamFeeWaiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="granted_exam_fee_waivers",
                        to="schools.schoolmembership",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_waivers",
                        to="quizzes.quiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_fee_waivers",
                        to="schools.schoolmembership",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "quiz"),
                        name="unique_exam_fee_waiver_per_student",
                    )
                ],
            },
        ),
    ]
