# Generated by Django 6.0.7 on 2026-08-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0002_schoolclass_suku360_id_teacherassignment_suku360_id_and_more",
        ),
        ("quizzes", "0012_backfill_submission_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="offerings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional: restrict this quiz or exam to specific class/subject offerings (useful when you teach the same subject to more than one class). Leave empty for a subject-wide quiz, open to every enrolled student - or, for an exam, every active student in the school.",
                related_name="quizzes",
                to="academics.subjectoffering",
            ),
        ),
    ]
