from django.urls import path
from . import views

urlpatterns = [
    path("<int:quiz_id>/start/", views.quiz_start_view, name="quiz_start"),
    path("<int:quiz_id>/take/", views.quiz_take_view, name="quiz_take"),
    path("result/<int:submission_id>/", views.quiz_result_view, name="quiz_result"),
    path("create-choice/", views.quiz_create_choice_view, name="quiz_create_choice"),
    path("create/", views.create_quiz_view, name="create_quiz"),
    path("<int:quiz_id>/add-question/", views.add_question_view, name="add_question"),
    path("ai-generate/", views.ai_generate_quiz_view, name="ai_generate_quiz"),
    path("<int:quiz_id>/publish/", views.publish_quiz_view, name="publish_quiz"),
    path("<int:quiz_id>/exam/begin/", views.start_exam_attempt_view, name="start_exam_attempt"),
    path("<int:quiz_id>/exam/consent/", views.exam_consent_view, name="exam_consent"),
    path("<int:quiz_id>/exam/take/<int:submission_id>/", views.exam_take_view, name="exam_take"),
    path("exam/attempt/<int:submission_id>/integrity-event/", views.exam_integrity_event_view, name="exam_integrity_event"),
    path("exam/attempt/<int:submission_id>/snapshot/", views.exam_snapshot_upload_view, name="exam_snapshot_upload"),
    path("<int:quiz_id>/exam/offerings/", views.select_exam_offerings_view, name="select_exam_offerings"),
    path("<int:quiz_id>/exam/roster/", views.exam_roster_view, name="exam_roster"),
    path("<int:quiz_id>/exam/roster/<int:student_id>/waive/", views.grant_exam_fee_waiver_view, name="grant_exam_fee_waiver"),
    path("<int:quiz_id>/exam/grading/", views.exam_grading_queue_view, name="exam_grading_queue"),
    path("exam/grading/attempt/<int:submission_id>/", views.exam_attempt_detail_view, name="exam_attempt_detail"),
    path("exam/grading/attempt/<int:submission_id>/clear-flag/", views.clear_exam_flag_view, name="clear_exam_flag"),
    path("<int:quiz_id>/exam/publish-results/", views.publish_exam_results_view, name="publish_exam_results"),
    path("generation-settings/", views.quiz_generation_settings_view, name="quiz_generation_settings"),
    path("bank/generate/", views.generate_bank_questions_view, name="generate_bank_questions"),
    path("bank/review/", views.bank_review_queue_view, name="bank_review_queue"),
    path("<int:quiz_id>/bank/", views.add_bank_questions_view, name="add_bank_questions"),
    path("assignments/create/", views.create_assignment_view, name="create_assignment"),
    path("assignments/<int:assignment_id>/rubric/", views.manage_rubric_view, name="manage_rubric"),
    path("assignments/<int:assignment_id>/", views.assignment_detail_view, name="assignment_detail"),
    path("assignments/<int:assignment_id>/submissions/", views.assignment_submissions_list_view, name="assignment_submissions_list"),
    path("assignments/grade/<int:submission_id>/", views.grade_assignment_view, name="grade_assignment"),
]