# Generated by Django 6.0.7 on 2026-08-22 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0007_school_report_signatures"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("study_ai", "Self-Study Hub"),
                            ("quiz_generation", "Quiz Generation"),
                            ("quiz_grading", "Quiz Grading"),
                            ("assignment_grading", "Assignment Grading"),
                            ("lesson_ai", "Lesson Notes"),
                            ("student_reports", "Student Reports"),
                            ("analytics_narrative", "Analytics Narratives"),
                        ],
                        max_length=30,
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("input_tokens", models.IntegerField(blank=True, null=True)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
                ("succeeded", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_events",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
