# Generated by Django 6.0.8 on 2026-09-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiusageevent",
            name="source",
            field=models.CharField(
                choices=[
                    ("study_ai", "Self-Study Hub"),
                    ("quiz_generation", "Quiz Generation"),
                    ("quiz_grading", "Quiz Grading"),
                    ("assignment_grading", "Assignment Grading"),
                    ("lesson_ai", "Lesson Notes"),
                    ("scheme_of_learning", "Scheme of Learning"),
                    ("student_notes", "Student Notes"),
                    ("student_reports", "Student Reports"),
                    ("analytics_narrative", "Analytics Narratives"),
                ],
                max_length=30,
            ),
        ),
    ]
