# Generated by Django 6.0.7 on 2026-08-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("schools", "0008_school_suku360_id_schoolmembership_suku360_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="suku360_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Suku360's own SchoolClass id, once synced.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="suku360_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Suku360's own TeachingAssignment id, once synced. Deliberately not unique: Suku360 scopes a teaching assignment per academic year, Nyansa scopes it per term (via offering) - one Suku360 assignment maps to one Nyansa row per term in that year, so the same suku360_id legitimately repeats across terms.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                condition=models.Q(("suku360_id__isnull", False)),
                fields=("school", "suku360_id"),
                name="unique_school_class_suku360_id",
            ),
        ),
    ]
